Update README.md
frap129/klipmi pull request #2
Opened 2024-06-27 19:34 UTC by Pukkahq

Updated install and added some help for errors

2024-07-09 16:47 UTC, frap129 approved these changes

2024-07-09 16:47 UTC, frap129 commented on README.md
> +    .venv/bin/nextion-fw-upload -b 115200 -ub 921600 /dev/ttyS1 ~/klipmi/hmi/openq1/Q1_UI.tft
klipmi is not specific to OpenQ1, it is extensible to many printer firmwares, printers, and screens. Any instructions documenting firmware flashing would need to be much more in depth and generic than this.

2024-07-09 16:47 UTC, frap129 commented on README.md
> +    http://IP OF PRINTER/access/api_key
Its much easier to get the API key using ~/moonraker/scripts/fetch_apikey.sh

2024-07-09 16:47 UTC, frap129 commented on README.md
> +If you see this error No such file or directory: '/root/printer_data/config/klipmi.toml' change the service user to mks
The guide works as written, this is unnecessary.

2024-07-09 17:31 UTC, frap129 requested changes
Earlier approval was an accident

2024-09-20 20:36 UTC, MicroSur commented on README.md
> +    http://IP OF PRINTER/access/api_key
mks@qidi-q1:~/moonraker/scripts$ ~/moonraker/scripts/fetch-apikey.sh
/home/mks/moonraker-env/bin/python: No module named lmdb

2024-09-20 22:58 UTC, MicroSur commented on README.md
> +If you see this error No such file or directory: '/root/printer_data/config/klipmi.toml' change the service user to mks
klipmi or klpmi
Errors with this.

2025-11-25 16:12 UTC, closed without merging